Para gerar um arquivo pdf a partir do Jupyter Notebook, você precisar ter instalado em seu computador:
    
    MiKTeX e Pandoc (Windows)
    LaTeX e Pandoc (Mac)
    TeX Live e Pandoc (linux)
    
Neste link você encontra todas as informações: http://pandoc.org/installing.html

## Computação com Numpy

In [1]:
# Importando o módulo Numpy
import numpy as np

<h2>Criando Estruturas de Dados NumPy</h2>

In [2]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40])

In [3]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15],[42, 78, 0]])

In [4]:
array1

array([10, 20, 30, 40])

In [5]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [6]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [7]:
# Verificando o formato (shape) do array
array2.shape

(2, 3)

In [8]:
# Verificando o número de dimensões
array2.ndim

2

<h2>Em Python TUDO é objeto, com métodos e atributos</h2>

### Método - realiza ação no objeto
### Atributo - característica do objeto

In [9]:
# Método
array2.max()

100

In [ ]:
# Atributo
array2.ndim

<h2>Criando estruturas de dados com arange</h2>

In [ ]:
array3 = np.arange(15)

In [ ]:
array3

In [ ]:
# Usando start/end (exclusive)
array4 = np.arange(0, 15, 5)

In [ ]:
array4

array([ 0,  5, 10])

<h2>Criando estruturas de dados com linspace</h2>

In [ ]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

<h2>Criando estruturas de dados com outras funções</h2>

<h3>numpy.zeros</h3>

In [ ]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8)); array6

<h3>numpy.ones</h3>

In [ ]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

<h3>numpy.eye</h3>

In [ ]:
# Produz uma Identitiy Matrix
array8 = np.eye(3); array8

<h3>numpy.diag</h3>

In [ ]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

<h3>numpy.random.rand</h3>

In [ ]:
# A função rand(n) produz uma sequência de números uniformemente distirbuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([ 0.54340494,  0.27836939,  0.42451759,  0.84477613,  0.00471886])

In [ ]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

<h3>numpy.empty</h3>

In [ ]:
array12 = np.empty((3,2)); array12

<h3>numpy.tile</h3>

In [ ]:
np.array([[9, 4], [3, 7]])

In [ ]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

In [ ]:
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

<h2>Tipos de Dados NumPy</h2>

In [ ]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [ ]:
array13

In [ ]:
array13.dtype

In [ ]:
array14 = np.array([2, 4, 6, 8])

In [ ]:
array14

In [ ]:
array14.dtype

In [ ]:
array15 = np.array([2.0, 4, 6, 8])

In [ ]:
array15.dtype

In [ ]:
array16 = np.array(['Análise','de','Dados','com Python'])

In [ ]:
array16.dtype

In [ ]:
array17 = np.array([True, False, True])

In [ ]:
array17.dtype

In [ ]:
array18 = np.array([7, -3, 5.24])

In [ ]:
array18.dtype

In [ ]:
array18.astype(int)

<h2>Operações com Arrays</h2>

In [ ]:
# Array começando por 0, com 30 elementos e multiplicado po 5
array19 = np.arange(0, 30) * 5

In [ ]:
array19

In [ ]:
array19 = np.arange(0, 30)

In [ ]:
array19

In [ ]:
# Elevando um array a potência
array20 = np.arange(5) ** 4

In [ ]:
array20

In [ ]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [ ]:
array21

In [ ]:
array22 = np.arange(0, 30,3) + 3
array23 = np.arange(1,11)

In [ ]:
array22

In [ ]:
array23

In [ ]:
# Subtração
array22 - array23

In [ ]:
# Soma
array22 + array23

In [ ]:
# Divisão
array22 / array23

In [ ]:
# Multiplicação
array22 * array23

In [ ]:
# Podemos ainda comprar arrays
array22 > array23

In [ ]:
arr1 = np.array([True,False,True,False])
arr2 = np.array([False,False,True, False])
np.logical_and(arr1, arr2)

### Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido

In [ ]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

C:\Users\RILDO\Anaconda3\lib\site-packages\ipykernel\__main__.py:257: RuntimeWarning: invalid value encountered in power


10000 loops, best of 3: 56.8 µs per loop


In [ ]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

The slowest run took 5.34 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 657 µs per loop


A métrica µs significa microsegundos.

# Fim